version: '3'

services:

  medical:
    image: medicallogregistry.azurecr.io/medicallogregistry:latest
    restart: always
    container_name: medical
    ports:
      - '80:8000'
      - "2222:2222"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ${WEBAPP_STORAGE_HOME}/credentials.json:/python-docke/credentials.json
      - ${WEBAPP_STORAGE_HOME}/token.json:/python-docke/token.json
